version: '3.9'

services:
  backend:
    container_name: fast_food_backend
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./env_vars/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fast_food_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_vars/.db

  redis:
    image: redis:7.2
    container_name: fast_food_redis
    ports:
     - 6379:6379

volumes:
  postgres_data:
