# Generated by Django 5.0.1 on 2024-01-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('client', 'Client')], default='client', max_length=20, verbose_name='user type'),
        ),
    ]
