# Generated by Django 5.0.1 on 2024-01-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fasd-food-images/', verbose_name='Image'),
        ),
    ]
